[build]
    functions = "netlify/functions/node-fetch"


[[redirects]]
    from = "/api/lyrics/*"
    to = "https://api.musixmatch.com/:splat"
    status = 200


[[redirects]]
    from = "/api/cover/*"
    to = "http://ws.audioscrobbler.com/:splat"
    status = 200

[[redirects]]
    from = "/api/lyrcs/"
    to = "/.netlify/functions/:splat"
    status = 200

[[redirects]]
    from = "/api/cover/"
    to = "/.netlify/functions/:splat"
    status = 200